### ISSUE TITLE
add changelog

### ISSUE THREAD

**Issue by leela52452** [woffs/tazapp-android#2]
can you please add changelog.
what is [CHANGELOG](https://en.m.wikipedia.org/wiki/Changelog) ?

**Comment by woffs** [comment]
- an f-droid compatible changelog can be found in https://github.com/woffs/tazapp-android/tree/master/tazapp/src/*/fastlane/metadata/android/*
- this request would belong upstream https://github.com/die-tageszeitung/tazapp-android
- feel free to send patches / open PRs
